### ISSUE TITLE
Panic when missing certain fields from 

### ISSUE THREAD

**Issue by kadonnelly13** [kadonnelly13/rdapq#6]
Error when running certain domains.  Most likely data is missing from the response from a secondary server.

```
./rdapq --domain google.com
```

```
Entities:panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/kadonnelly13/rdapq/services.prettyPrintDomainData({{0xc000320158, 0x6}, {0xc00001c2b8, 0x17}, {0xc000320180, 0xa}, {0x0, 0x0}, {0x0, 0x0, ...}, ...})
        /home/kdonnelly/Projects/rdapq/services/domain.go:222 +0xccf
github.com/kadonnelly13/rdapq/services.GetDomainData(0xc000118080, {0x6db30e, 0x23}, 0xc0001180a0)
        /home/kdonnelly/Projects/rdapq/services/domain.go:35 +0x298
main.main()
        /home/kdonnelly/Projects/rdapq/rdapq.go:25 +0x185
```

**Comment by kadonnelly13** [comment]
Fixed with https://github.com/kadonnelly13/rdapq/pull/7.  There is a need to come up with a more elegant way to handle empty fields that get returned from secondary servers.
